swagger: "2.0"

info:
  title: Software Engineering 2 Project
  description: This project is a software implementation of the original mockup realized during the Software Engineering 2 class at the University of Trento.
  version: 1.0.0
schemes:
  - https
host: enigmatic-savannah-48655.herokuapp.com
basePath: /

paths:
  /getMap:
    post:
        summary: get the path throught the destination, starting from the inserted street.
        description: send the departure and arrival point and return all the information needed to the path.
        parameters:
          - name: departure
            in: body
            description: departure point
            schema:
              required:
                - departure
                - arrival
              properties:
                departure:
                  type: string
                arrival:
                  type: string
        responses:
          200:
            description: return a JSON which contains an array of coordinates, departure and arrival location, route distance and route duration.
            schema:
              type: object
              properties:
                departureAddress:
                  type: string
                departureLocation:
                  $ref: "#/definitions/Location"
                arrivalAddress:
                  type: string
                arrivalLocation:
                  $ref: "#/definitions/Location"
                routeDistance:
                  type: string
                routeDutation:
                  type: string
                polyline:
                  $ref: "#/definitions/polyline"
          449:
            description: the departure and arrival points are not linked by any path in our database.

definitions:
    Location:
      type: object
      properties:
        lat:
          type: number
        lng:
          type: number
    polyline:
      type: array
      items:
        type: object
        properties:
          lat:
            type: number
          lng:
            type: number
